#include "dice.h"

void d6(int result)
{
    switch (result)
    {
    case 1:
        printf("+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+\n");
        printf("MMy-------------------------------------------:yMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                    -//-                    oMM\n");
        printf("MMo                  -mMMMMm-                  oMM\n");
        printf("MMo                  hMMMMMMh                  oMM\n");
        printf("MMo                  -mMMMMm-                  oMM\n");
        printf("MMo                    -//-                    oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMy::::::::::::::::::::::::::::::::::::::::::::yMM\n");
        printf("+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+\n");
        break;
    case 2:
        printf("+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+\n");
        printf("MMy-------------------------------------------:yMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                /sys/       oMM\n");
        printf("MMo                              `mMMMMMm`     oMM\n");
        printf("MMo                              .MMMMMMM.     oMM\n");
        printf("MMo                               /mMMMm/      oMM\n");
        printf("MMo                                 `.`        oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo        `.`                                 oMM\n");
        printf("MMo      /mMMMm/                               oMM\n");
        printf("MMo     .MMMMMMM.                              oMM\n");
        printf("MMo     `mMMMMMm`                              oMM\n");
        printf("MMo       /sys/                                oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMy::::::::::::::::::::::::::::::::::::::::::::yMM\n");
        printf("+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+\n");
        break;
    case 3:
        printf("+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+\n");
        printf("MMy-------------------------------------------:yMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                /sys/       oMM\n");
        printf("MMo                              `mMMMMMm`     oMM\n");
        printf("MMo                              .MMMMMMM.     oMM\n");
        printf("MMo                               /mMMMm/      oMM\n");
        printf("MMo                                 `.`        oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                    -//-                    oMM\n");
        printf("MMo                  -mMMMMm-                  oMM\n");
        printf("MMo                  hMMMMMMh                  oMM\n");
        printf("MMo                  -mMMMMm-                  oMM\n");
        printf("MMo                    -//-                    oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo        `.`                                 oMM\n");
        printf("MMo      /mMMMm/                               oMM\n");
        printf("MMo     .MMMMMMM.                              oMM\n");
        printf("MMo     `mMMMMMm`                              oMM\n");
        printf("MMo       /sys/                                oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMy::::::::::::::::::::::::::::::::::::::::::::yMM\n");
        printf("+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+\n");
        break;
    case 4:
        printf("+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+\n");
        printf("MMy-------------------------------------------:yMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo       /sys/                    /sys/       oMM\n");
        printf("MMo     `mMMMMMm`                `mMMMMMm`     oMM\n");
        printf("MMo     .MMMMMMM.                .MMMMMMM.     oMM\n");
        printf("MMo      /mMMMm/                  /mMMMm/      oMM\n");
        printf("MMo        `.`                      `.`        oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo        `.`                      `.`        oMM\n");
        printf("MMo      /mMMMm/                  /mMMMm/      oMM\n");
        printf("MMo     .MMMMMMM.                .MMMMMMM.     oMM\n");
        printf("MMo     `mMMMMMm`                `mMMMMMm`     oMM\n");
        printf("MMo       /sys/                    /sys/       oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMy::::::::::::::::::::::::::::::::::::::::::::yMM\n");
        printf("+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+\n");
        break;
    case 5:
        printf("+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+\n");
        printf("MMy-------------------------------------------:yMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo       /sys/                    /sys/       oMM\n");
        printf("MMo     `mMMMMMm`                `mMMMMMm`     oMM\n");
        printf("MMo     .MMMMMMM.                .MMMMMMM.     oMM\n");
        printf("MMo      /mMMMm/                  /mMMMm/      oMM\n");
        printf("MMo        `.`                      `.`        oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                    -//-                    oMM\n");
        printf("MMo                  -mMMMMm-                  oMM\n");
        printf("MMo                  hMMMMMMh                  oMM\n");
        printf("MMo                  -mMMMMm-                  oMM\n");
        printf("MMo                    -//-                    oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo        `.`                      `.`        oMM\n");
        printf("MMo      /mMMMm/                  /mMMMm/      oMM\n");
        printf("MMo     .MMMMMMM.                .MMMMMMM.     oMM\n");
        printf("MMo     `mMMMMMm`                `mMMMMMm`     oMM\n");
        printf("MMo       /sys/                    /sys/       oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMy::::::::::::::::::::::::::::::::::::::::::::yMM\n");
        printf("+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+\n");
        break;
    case 6:
        printf("+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+\n");
        printf("MMy-------------------------------------------:yMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo       /sys/                    /sys/       oMM\n");
        printf("MMo     `mMMMMMm`                `mMMMMMm`     oMM\n");
        printf("MMo     .MMMMMMM.                .MMMMMMM.     oMM\n");
        printf("MMo      /mMMMm/                  /mMMMm/      oMM\n");
        printf("MMo        `.`                      `.`        oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo       `:/:`                    `:/:`       oMM\n");
        printf("MMo      sMMMMMs                  sMMMMMs      oMM\n");
        printf("MMo     -MMMMMMM-                -MMMMMMM-     oMM\n");
        printf("MMo      sMMMMMs                  sMMMMMs      oMM\n");
        printf("MMo       `:/:`                    `:/:`       oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo        `.`                      `.`        oMM\n");
        printf("MMo      /mMMMm/                  /mMMMm/      oMM\n");
        printf("MMo     .MMMMMMM.                .MMMMMMM.     oMM\n");
        printf("MMo     `mMMMMMm`                `mMMMMMm`     oMM\n");
        printf("MMo       /sys/                    /sys/       oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMo                                            oMM\n");
        printf("MMy::::::::::::::::::::::::::::::::::::::::::::yMM\n");
        printf("+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+\n");
        break;
    }
    printf("\n");
}

void d20(int result)
{
    printf("                   .++.                   \n");
    printf("                :smNMMNms:                \n");
    printf("            `/yNdo- NN -odNy/`            \n");
    printf("         -odNy/`    NN    `/yNdo-         \n");
    printf("     `/yNdo-        NN        -omNy/`     \n");
    printf("  -odNy/.       ``..NN..``       .+hNdo-  \n");
    printf("yNMMMddmmmNNNNmmmmdMMMMdmmmmNNNNmmmddMMMNy\n");
    printf("MMy....``         oMyyMo         ``....yMM\n");
    printf("MMM-             yM+  oMy             -MMM\n");
    printf("MmmN.          `hM/    /Mh`          .NmmM\n");
    printf("Mh-Md         .mN-      :Nm.        `dN-hM\n");
    printf("Mh /My       -Nm.        .mN-       yM/ hM\n");
    printf("Mh  sM+     :Nd`    %01d    `dN:     +Ms  hM\n", result);
    printf("Mh   hM:   +My             `hM+   :Mh   hM\n");
    printf("Mh   `mN. sMo                sMs .Nm`   hM\n");
    printf("Mh    -NmhM+                  +MhmN.    hM\n");
    printf("Mh   `:hMMNhhhhhhhhhhhhhhhhhhhhNMMh-`   hM\n");
    printf("Mm+ymNds+mMy------------------yMm+sdNmy+mM\n");
    printf("mMMd-     oMh.              .hMo     -dMMd\n");
    printf(" .+hNh+.   .hMo            oMh.   .odNy/` \n");
    printf("     :smms:` /Nm:        :mN/ `:smms:     \n");
    printf("        .+hNh+-sMy`    `yMs-+hNh+.        \n");
    printf("           `:smmdMN+  +NMdmms:            \n");
    printf("               .+hMMddMMh+.               \n");
    printf("                  `/ss:`                  \n");
    printf("\n");
}
